---
## olcne prerequisities setting
#  - name: install olcen yum repo
#    yum:
#      name: oracle-olcne-release-el7
#      state: present

#  - name: Disable olcne 1.0 repo
#    shell: |
#      yum-config-manager --disable ol7_olcne

#  - name: Enable ol7_olcne11, ol7_kvm_utils, ol7_addons, ol7_latest and ol7_UEKR5 repos
#    shell: |
#      yum-config-manager --enable ol7_olcne11 ol7_kvm_utils ol7_addons ol7_latest ol7_UEKR5
- name: update yum repositories cache
  shell: |
    yum makecache


#  - name: Install chronyd service
#    yum:
#      name: chrony
#      state: present
#  - name: Enable chronyd Service
#    systemd:
#      name: chronyd
#      state: started
#      enabled: yes

#  - name: Disable swap, br_netfilter and SELinux
#    shell: |
#      swapoff -a
#      sed -i 's/^.*swap/#&/' /etc/fstab
#      modprobe br_netfilter
#      sh -c 'echo "br_netfilter" > /etc/modules-load.d/br_netfilter.conf'
#      sed -i 's/^SELINUX=enforcing/SELINUX=disabled/' /etc/selinux/config
#      /sbin/setenforce 0

- name: Bridge Tunable Parameters
  shell: |
    sh -c 'echo "net.bridge.bridge-nf-call-ip6tables = 1" >> /etc/sysctl.conf'
    sh -c 'echo "net.bridge.bridge-nf-call-iptables = 1" >> /etc/sysctl.conf'
    sh -c 'echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf'
    /sbin/sysctl -p /etc/sysctl.conf

- name: Configure firewalld on operator
  shell: |
    firewall-cmd --zone=public --permanent --add-port=8091/tcp
    firewall-cmd --reload
  when: inventory_hostname in groups['operator']


- name: Configure firewalld on masters
  shell: |
# these lines for multi-master firewall 
    firewall-cmd --zone=public --permanent --add-port=10251/tcp
    firewall-cmd --zone=public --permanent --add-port=10252/tcp
    firewall-cmd --zone=public --permanent --add-port=2379/tcp
    firewall-cmd --zone=public --permanent --add-port=2380/tcp
# these lines for single-master firewall
    firewall-cmd --zone=trusted --add-interface=cni0 --permanent
    firewall-cmd --zone=public --permanent --add-port=8090/tcp
    firewall-cmd --zone=public --permanent --add-port=10250/tcp
    firewall-cmd --zone=public --permanent --add-port=10255/tcp
    firewall-cmd --zone=public --permanent --add-port=8472/udp
    firewall-cmd --zone=public --permanent --add-port=6443/tcp
      
    firewall-cmd --reload
  when: inventory_hostname in groups['master']

- name: Configure firewalld on workers node
  shell: |
    firewall-cmd --zone=trusted --add-interface=cni0 --permanent
    firewall-cmd --zone=public --permanent --add-port=8090/tcp
    firewall-cmd --zone=public --permanent --add-port=10250/tcp
    firewall-cmd --zone=public --permanent --add-port=10255/tcp
    firewall-cmd --zone=public --permanent --add-port=8472/udp

    firewall-cmd --reload
  when: inventory_hostname in groups['worker']


